### ISSUE TITLE
URL responder doesn't properly parse when URL surrounded by character such as parenthesis

### ISSUE THREAD

**Issue by kinabalu** [evanchooly/javabot#108]
This was the test URL (https://eugeneciurana.com/entry/full-disk-encryption-privacy-revisited-and-what-it-means-to-you)

should work with anything.  javabot does not respond

**Comment by evanchooly** [comment]
I think you're just seeing no response because the url and the title match so completely.  @jottinger ?

**Comment by kinabalu** [comment]
Nope, I tested it in channel with a shortened URL with no discernible words (http://prsm.tc/Q429ab) works as well

**Comment by jottinger** [comment]
I'm going to fix the plugin to detect the protocol, and start resolution there, because that makes sense. However, trailing punctuation is going to yield a broken URL. Thus:

(http://foo.com) will try to resolve "http://foo.com)" because reliably detecting the closing parenthesis is a drag. We can probably do the most common cases, but actually matching the characters creates a path of madness and it's not that big of a deal to me.
