### ISSUE TITLE
URL lookup and other functions are not using UTF-8

### ISSUE THREAD

**Issue by dmlloyd** [evanchooly/javabot#203]
For whatever reason, javabot is either not reading or not emitting UTF-8:

```
<dmlloyd> here it is: https://github.com/evanchooly/javabot/issues/202
<javabot> dmlloyd's title: "Enhance RFC lookup with section and page references  Issue #202  evanchooly/javabot  GitHub"
```
In the above example, there are missing bullets between "references" and "Issue", and between "javabot" and "GitHub".

A more obvious example:
```
<dmlloyd> http://www.koreaherald.com/view.php?ud=20180104000796&kr=1
<javabot> dmlloyd's title: "()    "
```

**Comment by whaley** [comment]
It's by design... see https://github.com/evanchooly/javabot/blob/master/src/main/kotlin/javabot/operations/URLTitleOperation.kt#L84-L88

Since ##java is effectively anglophone only, and that  there's the possibility for abuse, I suggest we leave ascii only characters for now and elect to not show a title if the title is greater than N number of characters where N is something sensible like 20.
